### ISSUE TITLE
Remove generation of overlaped schistos 

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [LucasSilvaFerreira/synthetic_deep_schisto#3]
We need to create an heuristic method that avoid the schisto overlapping in image generation.

**Comment by vmesel** [comment]
Is this an overlapping case?
![train_image_132_ 3 0](https://cloud.githubusercontent.com/assets/4984147/17925099/f1a874f6-69c1-11e6-8de4-3f81797edf85.png)

**Comment by LucasSilvaFerreira** [comment]
yes,
exactly

**Comment by vmesel** [comment]
@LucasSilvaFerreira shouldn't we generate a list with the schisto positions and them compare if any schisto is in the same x and y?

**Comment by vmesel** [comment]
Solved by lucas on last commit!
